image: Visual Studio 2015
version: 0.7.{build}
install:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/install-android-sdk.ps1?v=2'))
- ps: $sdks = Get-AndroidSDKs |? { $_.name -like 'sdk platform*API 24*' -or $_.name -like 'Google APIs, Android API 24' } 
- ps: Install-AndroidSDK -sdks $sdks
build_script:
- cmd: ./build.cmd
artifacts:
- path: artifacts/*
test: off